name: check

on:
  workflow_dispatch:
    

jobs:
  test:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Display
      run: |
        mount | grep -i nexec
 
